baseURL = "https://blog.trucuk.com"
languageCode = "id"
title = "Mediumish"
summaryLength = 25
copyright = "Muh Cahyo - All rights reserved"
enableEmoji = true
#publishDir = "docs"
disqusShortname = "tixnime-1"
googleAnalytics = "UA-174513993-1"
enableRobotsTXT = true
paginate = 6

[imaging]
  quality = 50

[output]
  home = ["HTML"]
  page = ["HTML", "AMP", "RSS"]
  taxonomy = ["HTML", "AMP", "RSS"]
  term = ["HTML", "AMP", "RSS"]
  section = ["HTML", "AMP", "RSS"]

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 0
    [minify.tdewolff.html]
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 0
    [minify.tdewolff.json]
      precision = 0
    [minify.tdewolff.svg]
      precision = 0
    [minify.tdewolff.xml]
      keepWhitespace = false

[params]
  logo = "/images/logo.png"
  description ="Blog Pribadi Orang Gabut"
  #mailchimp = "you can provide a mailchimp-link here"
  ThemeColor = "#333"

[params.author]
  name = "muh cahyo"
  thumbnail = "/images/author.png"
  description = "Creator of this blog."

[params.index]
  picture = "/images/author.png"
  title = "Muh Cahyo"
  subtitle = "Be Your Self And Always Surrender"
  mdtext = '''
  Blog Pribadi Oranbg Gabut\
  Yamg Suka Nonton Anime, Baca Komik, Main Game dan Sedikit mengerti Progeming
'''
  alertbar = false

[params.social]
  github = "muhcahyo2"
  #linkedin = "<username>"
  #xing = "<username>"
  #medium = "<username>"
  #twitter = "<username>"
  instagram = "muhcahyo2"
  facebook = "muh.j.cahyo"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"
